#            _    _       _      _____
#           | |  | |     | |    / ____|
#           | |__| |_   _| |__ | |     ___  _ __ ___
#           |  __  | | | | '_ \| |    / _ \| '__/ _ \
#           | |  | | |_| | |_) | |___| (_) | | |  __/
#           |_|  |_|\__,_|_.__/ \_____\___/|_|  \___|  1.0


# ------------> BungeeCord <--------------
# For using this, you will need to have enabled the mysql otherwise it won't work and may show up some errors
# This is meant to notify all your StaffMembers about the Ban Alerts, Report Alerts, and so on.
# The Mysql is needed cuz that's where the plugin is going to get all the data like: the reason, the name...
bungeecord:
  enabled: true # By default is set to true, otherwise, the plugin won't work
  server: "lobby" # This is the name of the server(default: lobby)!
  server_prefix: " &7[&a%server%&7] "

# ------------> Language <--------------
# Select the Language you want to use (Currently supported: EN_NA & ES_CL)
language: "EN_NA"

# ------------> Random Configs <--------------
# Here are random Configs that are alone.
spawnmobs: false


# ------------> Spawn Settings <--------------
# Spawn Settings
spawn:
  world:
  x:
  y:
  z:
  tp_on_join: true

# ------------> Blocked Commands <--------------
blocked_commands:
  - ""

# ------------> Blocked Commands <--------------
launchpad:
  enabled: true
  pressure_plate: "STONE_PRESSURE_PLATE"
  block_under: "REDSTONE_BLOCK"
  power: 2 # The of the launch pad

# ------------> Custom Sounds <--------------
# Here is a list of all the sounds: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
sounds: true
custom_sounds:
  launchpad: "ENTITY_IRON_GOLEM_ATTACK"

# ------------> PARTICLES <----------
# Here is a list of all the particles available: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Effect.html
